### ISSUE TITLE
Should we move this repo under dandisets/README

### ISSUE THREAD

**Issue by yarikoptic** [dandisets/datasets#5]
or some other pinned repository within dandisets organization, so people could easily find it?

**Comment by satra** [comment]
i actually don't know what this repo should do :) i was just using it for issues for the dandisets organization.

**Comment by yarikoptic** [comment]
;-) it could be a superdataset to install all datasets recursively. But also to collect issues as such. In readme we could point to datalad, otherwise not clear what to eat them with

**Comment by satra** [comment]
+1 on datalad superset - should we call it dandisuperset or dandilad ?

**Comment by satra** [comment]
if a superset, we can move this repo to dandisets and pin it.

**Comment by satra** [comment]
move to org. we could perhaps use this as a superset as discussed here.
